/**
 * English UN Resolution Operative Phrases
 *
 * These are the standard phrases used to begin operative clauses
 * in English-language UN resolutions.
 */

export const englishOperativePhrases: string[] = [
	'accepts',
	'acknowledges',
	'adopts',
	'affirms',
	'reaffirms',
	'also affirms',
	'also calls upon',
	'also decides',
	'also encourages',
	'also expresses',
	'also notes',
	'also recommends',
	'also requests',
	'also urges',
	'appeals',
	'appreciates',
	'approves',
	'authorizes',
	'calls for',
	'calls upon',
	'further calls upon',
	'commends',
	'condemns',
	'strongly condemns',
	'confirms',
	'congratulates',
	'considers',
	'decides',
	'further decides',
	'declares',
	'declares accordingly',
	'demands',
	'deplores',
	'designates',
	'directs',
	'draws attention',
	'emphasizes',
	'encourages',
	'strongly encourages',
	'endorses',
	'expresses',
	'expresses appreciation',
	'expresses concern',
	'expresses its appreciation',
	'expresses its concern',
	'expresses its hope',
	'further encourages',
	'further invites',
	'further proclaims',
	'further recommends',
	'further requests',
	'further resolves',
	'further urges',
	'has resolved',
	'hopes',
	'instructs',
	'invites',
	'notes',
	'notes with appreciation',
	'notes with concern',
	'notes with satisfaction',
	'proclaims',
	'reaffirms',
	'recalls',
	'recognizes',
	'recommends',
	'regrets',
	'reiterates',
	'reminds',
	'renews',
	'repeats',
	'requests',
	'resolves',
	'solemnly affirms',
	'stresses',
	'strongly condemns',
	'strongly urges',
	'suggests',
	'supports',
	'takes note',
	'transmits',
	'trusts',
	'underlines',
	'underscores',
	'urges',
	'welcomes'
];
