/**
 * English UN Resolution Preamble Phrases
 *
 * These are the standard phrases used to begin preamble clauses
 * in English-language UN resolutions.
 */

export const englishPreamblePhrases: string[] = [
	'acknowledging',
	'affirming',
	'reaffirming',
	'alarmed',
	'deeply alarmed',
	'appreciating',
	'approving',
	'aware',
	'fully aware',
	'bearing in mind',
	'believing',
	'firmly believing',
	'commending',
	'concerned',
	'deeply concerned',
	'gravely concerned',
	'confident',
	'congratulating',
	'conscious',
	'considering',
	'convinced',
	'firmly convinced',
	'declaring',
	'deeply conscious',
	'deeply convinced',
	'deeply disturbed',
	'deeply regretting',
	'deploring',
	'desiring',
	'determined',
	'firmly determined',
	'disappointed',
	'disturbed',
	'emphasizing',
	'encouraging',
	'endorsing',
	'expecting',
	'expressing appreciation',
	'expressing concern',
	'expressing deep concern',
	'expressing gratitude',
	'expressing its appreciation',
	'expressing its satisfaction',
	'expressing satisfaction',
	'fulfilling',
	'fully alarmed',
	'fully aware',
	'fully believing',
	'further deploring',
	'further recalling',
	'gravely concerned',
	'guided by',
	'having adopted',
	'having considered',
	'having decided',
	'having devoted attention',
	'having examined',
	'having heard',
	'having received',
	'having reviewed',
	'having studied',
	'keeping in mind',
	'mindful',
	'noting',
	'noting further',
	'noting with appreciation',
	'noting with approval',
	'noting with concern',
	'noting with deep concern',
	'noting with grave concern',
	'noting with regret',
	'noting with satisfaction',
	'observing',
	'preoccupied',
	'realizing',
	'reaffirming',
	'recalling',
	'further recalling',
	'recognizing',
	'referring',
	'regretting',
	'deeply regretting',
	'reiterating',
	'reminding',
	'seeking',
	'stressing',
	'strongly condemning',
	'supporting',
	'taking into account',
	'taking into consideration',
	'taking note',
	'underlining',
	'understanding',
	'viewing with appreciation',
	'welcoming',
	'with satisfaction'
];
